name: Deploy

on:
    push:
        branches: [main]

concurrency:
    group: deploy
    cancel-in-progress: true

jobs:
    analyze:
        uses: ./.github/workflows/codeql.yml
    test:
        uses: ./.github/workflows/test.yml
    build:
        needs: [analyze, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: ./.github/actions/setup-environment
            - name: Build
              run: pnpm run build
            - name: Upload artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./build
    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
