name: Test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - uses: ./.github/actions/setup-environment
            - name: Build
              run: pnpm run build
